import{createClient}from'https://esm.sh/@supabase/supabase-js@2';import{SUITS,dealHands,newState,applyBid,setTrump,legalCards,applyCard}from'./games/tarneeb/engine.js';
const supabase=createClient('https://gzgngkywjyanxicmwxlc.supabase.co','sb_publishable_Jyr7D3mH7WRXfG5V1v7gcw_I3QhtL3j');const $=id=>document.getElementById(id),red=s=>s==='♥'||s==='♦';let authMode='login',G=null,currentRoom=null,channel=null,aiTimer=null;
function show(id,on){$(id).classList.toggle('hidden',!on)}function msg(t){$('msg').textContent=t||''}function landing(){['auth','home','room','game','socialHub'].forEach(x=>show(x,false));show('landing',false);show('approvedHome',true);msg('')}window.showApprovedHome=landing;window.openApprovedMenu=()=>openSocial('profile');window.createStory=()=>openSocial('profile');window.createPost=()=>openSocial('feed');function openLogin(){authMode='login';$('authTitle').textContent='تسجيل الدخول';$('authSubmit').textContent='دخول';show('landing',false);show('auth',true)}function openSignup(){authMode='signup';$('authTitle').textContent='إنشاء حساب';$('authSubmit').textContent='إنشاء الحساب';show('landing',false);show('auth',true)}window.openLogin=openLogin;window.openSignup=openSignup;window.backLanding=landing;
window.guestPlay=()=>{msg('');show('approvedHome',false);show('landing',false);show('home',false);startGame(true)};
window.submitAuth=async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password)return $('authMsg').textContent='أدخل البريد الإلكتروني وكلمة المرور.';const r=authMode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)return $('authMsg').textContent=r.error.message;$('authMsg').textContent='تم بنجاح';show('auth',false);show('home',true)};
window.signOut=async()=>{await supabase.auth.signOut();landing()};
async function createRoom(){const{data,error}=await supabase.rpc('tarneeb_create_game');if(error)return msg(error.message);const code=typeof data==='string'?data:data?.room_code;if(!code)return msg('تعذر إنشاء الغرفة');const r=await supabase.from('tarneeb_games').select('id,room_code,status').eq('room_code',code).single();if(r.error)return msg(r.error.message);showRoom(r.data.id,r.data.room_code)}window.createRoom=createRoom;
window.joinRoom=async()=>{const code=$('roomCode').value.trim().toUpperCase();if(!code)return msg('أدخل رمز الغرفة');const{data,error}=await supabase.rpc('join_tarneeb_room',{p_room_code:code});if(error)return msg(error.message);showRoom(data.room_id,data.room_code)};
async function showRoom(id,code){currentRoom=id;$('code').textContent=code;show('home',false);show('room',true);await loadPlayers();if(channel)await supabase.removeChannel(channel);channel=supabase.channel('room-'+id).on('postgres_changes',{event:'*',schema:'public',table:'tarneeb_room_players',filter:'room_id=eq.'+id},loadPlayers).subscribe()}
async function loadPlayers(){if(!currentRoom)return;const{data,error}=await supabase.from('tarneeb_room_players').select('seat,user_id').eq('room_id',currentRoom).order('seat');if(error)return msg(error.message);$('players').innerHTML='';for(let i=1;i<=4;i++){const p=(data||[]).find(x=>x.seat===i),d=document.createElement('div');d.className='seat';d.innerHTML=`<span>المقعد ${i} · الفريق ${i%2?1:2}</span><span class="badge">${p?'متصل':'بانتظار لاعب'}</span>`;$('players').appendChild(d)}$('roomStatus').textContent=`${(data||[]).length} / 4 لاعبين`;$('startBtn').disabled=(data||[]).length<4}
window.leaveRoom=async()=>{if(channel)await supabase.removeChannel(channel);currentRoom=null;show('room',false);show('home',true)};
function startGame(demo){if(aiTimer)clearTimeout(aiTimer);G={demo,round:1,score:[0,0],state:newState(dealHands(),0,[0,0]),log:['تم توزيع 52 ورقة · 13 ورقة لكل لاعب.']};show('landing',false);show('home',false);show('room',false);show('socialHub',false);show('game',true);render();runAI()}
function render(){$('score0').textContent=G.score[0];$('score1').textContent=G.score[1];const s=G.state;$('roundLabel').textContent=`الجولة ${G.round} · الأكلة ${s.trickNo}/13`;$('stateInfo').textContent=s.phase==='bid'?`المزايدة · دور اللاعب ${s.bidTurn+1} · أعلى طلب ${s.highBid<7?'لا يوجد':s.highBid}`:s.phase==='trump'?`اللاعب ${s.bidWinner+1} اختار الطلب ${s.highBid} · اختر الحكم`:s.phase==='play'?`الحكم ${s.trump} · دور اللاعب ${s.turn+1}`:`انتهت الجولة · الفريق ${s.roundResult.team+1} أخذ ${s.roundResult.made} أكلة`;$('bidBox').classList.toggle('hidden',!(s.phase==='bid'&&s.bidTurn===0));$('trumpBox').classList.toggle('hidden',!(s.phase==='trump'&&s.bidWinner===0));$('bidInfo').textContent=`أعلى طلب حالي: ${s.highBid<7?'لا يوجد':s.highBid}`;$('bids').innerHTML=[7,8,9,10,11,12,13].map(n=>`<button class="btn btn-primary" ${n<=s.highBid?'disabled':''} onclick="bid(${n})">${n}</button>`).join('');$('trumps').innerHTML=SUITS.map(x=>`<button class="btn btn-secondary" onclick="chooseTrump('${x}')">${x}</button>`).join('');$('trick').innerHTML=s.trick.map(x=>`<div class="played">لاعب ${x.player+1}<br><span class="${red(x.card.s)?'red':''}">${x.card.r+x.card.s}</span></div>`).join('');const legal=s.phase==='play'&&s.turn===0?legalCards(s,0):[];$('hand').innerHTML=s.players[0].hand.map((c,i)=>{const ok=legal.some(x=>x.s===c.s&&x.r===c.r);return `<button class="cardplay ${red(c.s)?'red':''}" ${ok?'':'disabled'} onclick="playHuman(${i})">${c.r+c.s}</button>`}).join('');$('log').innerHTML=G.log.slice(-14).map(x=>'• '+x).join('<br/>')}
window.bid=n=>{try{G.state=applyBid(G.state,0,n);G.log.push(`أنت زايدت ${n}.`);render();runAI()}catch(e){msg(e.message)}};window.chooseTrump=t=>{try{G.state=setTrump(G.state,0,t);G.log.push(`اخترت الحكم ${t}.`);render();runAI()}catch(e){msg(e.message)}};window.playHuman=i=>{const c=G.state.players[0].hand[i];try{G.state=applyCard(G.state,0,c);G.log.push(`لعبت ${c.r}${c.s}.`);afterMove()}catch(e){msg(e.message)}};
function aiBid(){const s=G.state,p=s.bidTurn,h=s.players[p].hand,high=h.filter(c=>c.v>=11).length,proposal=Math.min(13,Math.max(7,7+Math.floor(high/2)));return proposal<=s.highBid?null:proposal}
const AI_DELAY=720;
function runAI(){if(!G||!G.demo)return;if(aiTimer)clearTimeout(aiTimer);const s=G.state;if(s.phase==='round_end'){afterMove();return}if(s.phase==='bid'&&s.bidTurn!==0){aiTimer=setTimeout(()=>{try{const p=s.bidTurn,b=aiBid();G.state=applyBid(G.state,p,b);G.log.push(b?`اللاعب ${p+1} زايد ${b}.`:`اللاعب ${p+1} مرّر.`);render();runAI()}catch(e){msg(e.message)}},AI_DELAY);return}if(s.phase==='trump'&&s.bidWinner!==0){aiTimer=setTimeout(()=>{const p=s.bidWinner,h=s.players[p].hand,count=Object.fromEntries(SUITS.map(x=>[x,0]));h.forEach(c=>count[c.s]++);const t=SUITS.reduce((best,x)=>count[x]>count[best]?x:best,SUITS[0]);G.state=setTrump(G.state,p,t);G.log.push(`اللاعب ${p+1} اختار الحكم ${t}.`);render();runAI()},AI_DELAY);return}if(s.phase==='play'&&s.turn!==0){aiTimer=setTimeout(()=>{try{const p=s.turn,legal=legalCards(s,p);let c=legal.slice().sort((a,b)=>b.v-a.v)[0];if(s.leadSuit){const tr=legal.filter(x=>x.s===s.trump);c=(tr.length?tr:legal).slice().sort((a,b)=>b.v-a.v)[0]}G.state=applyCard(G.state,p,c);G.log.push(`اللاعب ${p+1} لعب ${c.r}${c.s}.`);afterMove()}catch(e){msg(e.message)}},AI_DELAY)}}
function afterMove(){render();if(G.state.phase==='round_end'){G.score=G.state.roundResult.scores;G.log.push(`نتيجة الجولة: ${G.score[0]} - ${G.score[1]}.`);render();if(Math.max(...G.score)>=31){G.log.push('🏆 انتهت المباراة!');render();return}setTimeout(()=>{G.round++;G.state=newState(dealHands(),(G.round-1)%4,G.score);G.log.push('جولة جديدة · تم توزيع 52 ورقة.');render();runAI()},1600)}else runAI()}
window.backHome=()=>{if(aiTimer)clearTimeout(aiTimer);G=null;show('game',false);if(currentRoom)show('room',true);else show('landing',true)};landing();
import './ui-enhance.js?v=20260823-v4';import './social-ui.js?v=20260823-v4';