import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.112.3/+esm';
const sb=createClient('https://gzgngkywjyanxicmwxlc.supabase.co','sb_publishable_Jyr7D3mH7WRXfG5V1v7gcw_I3QhtL3j');
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]));
let currentUser=null,currentConversation=null,poll=null;
async function user(){const{data}=await sb.auth.getUser();return data.user}
async function ensureConversation(otherId){const u=currentUser;if(!u||!otherId||u.id===otherId)return null;const{data:mine}=await sb.from('conversation_members').select('conversation_id').eq('user_id',u.id);const ids=(mine||[]).map(x=>x.conversation_id);if(ids.length){const{data:shared}=await sb.from('conversation_members').select('conversation_id').eq('user_id',otherId).in('conversation_id',ids);if(shared?.length)return shared[0].conversation_id}
 const{data:c,error}=await sb.from('conversations').insert({is_group:false,created_by:u.id}).select('id').single();if(error)throw error;const{error:e1}=await sb.from('conversation_members').insert({conversation_id:c.id,user_id:u.id});if(e1)throw e1;const{error:e2}=await sb.from('conversation_members').insert({conversation_id:c.id,user_id:otherId});if(e2)throw e2;return c.id}
async function loadConversations(){const{data:members,error}=await sb.from('conversation_members').select('conversation_id,last_read_at').eq('user_id',currentUser.id);if(error)throw error;const ids=(members||[]).map(x=>x.conversation_id);if(!ids.length)return[];const{data:cs,error:ce}=await sb.from('conversations').select('id,is_group,title,created_at').in('id',ids).order('created_at',{ascending:false});if(ce)throw ce;const out=[];for(const c of cs||[]){const{data:ms}=await sb.from('conversation_members').select('user_id').eq('conversation_id',c.id);const other=(ms||[]).find(x=>x.user_id!==currentUser.id)?.user_id;if(other){const{data:p}=await sb.from('profiles').select('id,display_name,username,avatar_url,verified,is_online').eq('id',other).maybeSingle();c.other=p||{id:other,display_name:'مستخدم'}}out.push(c)}return out}
async function renderMessages(){if(!currentConversation)return;const{data,error}=await sb.from('messages').select('id,sender_id,body,created_at,message_type,media_url').eq('conversation_id',currentConversation).is('deleted_at',null).order('created_at',{ascending:true}).limit(200);if(error){$('chatStatus').textContent=error.message;return}const box=$('chatMessages');box.innerHTML=(data||[]).map(m=>`<div class="chat-bubble ${m.sender_id===currentUser.id?'mine':'theirs'}"><div>${esc(m.body||'')}</div><small>${new Date(m.created_at).toLocaleTimeString('ar',{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="chat-empty">ابدأ المحادثة 👋</div>';box.scrollTop=box.scrollHeight}
async function openConversation(id,title){currentConversation=id;$('chatTitle').textContent=title||'محادثة';$('chatPanel').classList.remove('hidden');await renderMessages();subscribeRealtime();}
function subscribeRealtime(){if(!currentConversation)return;if(window.__kingsChatChannel)sb.removeChannel(window.__kingsChatChannel);window.__kingsChatChannel=sb.channel('kings-chat-'+currentConversation).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`conversation_id=eq.${currentConversation}`},()=>renderMessages()).subscribe();clearInterval(poll);poll=setInterval(renderMessages,5000)}
async function send(){const input=$('chatInput'),body=input.value.trim();if(!body||!currentConversation)return;const{error}=await sb.from('messages').insert({conversation_id:currentConversation,sender_id:currentUser.id,body,message_type:'text'});if(error){$('chatStatus').textContent=error.message;return}input.value='';await renderMessages()}
async function render(){currentUser=await user();if(!currentUser){$('socialContent').innerHTML='<div class="social-card"><strong>المحادثات</strong><span>سجّل الدخول أولاً لاستخدام Messenger.</span></div>';return}const cs=await loadConversations();$('socialContent').innerHTML=`<div class="chat-layout"><aside class="chat-list"><div class="social-card"><strong>المحادثات</strong><span>رسائل خاصة بينك وبين أصدقائك.</span></div><div id="chatList">${cs.map(c=>`<button class="chat-row" data-chat="${c.id}"><div class="small-avatar">${esc((c.other?.display_name||'م')[0])}</div><div><strong>${esc(c.other?.display_name||c.title||'محادثة')}</strong><small>${c.other?.is_online?'🟢 متصل':'⚪ غير متصل'}</small></div></button>`).join('')||'<div class="chat-empty">لا توجد محادثات بعد. افتح الأصدقاء وابدأ محادثة.</div>'}</div></aside><section id="chatPanel" class="chat-panel hidden"><header class="chat-header"><button id="chatBack" class="btn btn-secondary" type="button">رجوع</button><strong id="chatTitle">محادثة</strong></header><div id="chatMessages" class="chat-messages"></div><div class="chat-compose"><input id="chatInput" maxlength="2000" placeholder="اكتب رسالة..." autocomplete="off"><button id="chatSend" class="btn btn-primary" type="button">إرسال</button></div><div id="chatStatus" class="status-line"></div></section></div>`;document.querySelectorAll('[data-chat]').forEach(b=>b.onclick=async()=>{const c=cs.find(x=>x.id===b.dataset.chat);await openConversation(c.id,c.other?.display_name||'محادثة')});$('chatSend').onclick=send;$('chatInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};$('chatBack').onclick=()=>{$('chatPanel').classList.add('hidden');currentConversation=null;clearInterval(poll);if(window.__kingsChatChannel)sb.removeChannel(window.__kingsChatChannel)}}
window.openMessages=async()=>{const hub=$('socialHub');hub.classList.remove('hidden');$('socialTitle').textContent='المحادثات';$('socialStatus').textContent='جارٍ تحميل المحادثات...';await render();$('socialStatus').textContent='المحادثات جاهزة.'};
window.startChatWith=async otherId=>{currentUser=await user();if(!currentUser)return;try{const id=await ensureConversation(otherId);const{data:p}=await sb.from('profiles').select('display_name,username').eq('id',otherId).maybeSingle();await window.openMessages();await openConversation(id,p?.display_name||p?.username||'محادثة')}catch(e){$('socialStatus').textContent=e.message||'تعذر إنشاء المحادثة.'}};
