const css=document.createElement('link');css.rel='stylesheet';css.href='./ui-enhance.css?v=20260823-v4';document.head.appendChild(css);
const SUITS=new Set(['♠','♥','♦','♣']);
const splitCard=value=>{const t=value.trim();const m=t.match(/(10|[2-9]|J|Q|K|A)([♠♥♦♣])$/);return m?{rank:m[1],suit:m[2]}:null};
const countForRank=r=>{const n=Number(r);return Number.isFinite(n)&&n>=2&&n<=10?n:0};
function cardFace(rank,suit){const root=document.createElement('span');root.className='premium-card-face';const corner=document.createElement('span');corner.className='card-corner';corner.innerHTML=`<b>${rank}</b><i>${suit}</i>`;const center=document.createElement('span');center.className='card-center';const n=countForRank(rank);if(n){for(let i=0;i<n;i++){const p=document.createElement('i');p.textContent=suit;p.className='pip';center.appendChild(p)}}else{center.innerHTML=`<b class="face-rank">${rank}</b><i class="face-suit">${suit}</i>`}const bottom=document.createElement('span');bottom.className='card-corner bottom';bottom.innerHTML=`<b>${rank}</b><i>${suit}</i>`;root.append(corner,center,bottom);return root}
function decorateHand(){document.querySelectorAll('#hand .cardplay').forEach(btn=>{if(btn.dataset.decorated)return;const c=splitCard(btn.textContent);if(!c)return;btn.textContent='';btn.append(cardFace(c.rank,c.suit));btn.dataset.decorated='1';});}
function decorateTrick(){document.querySelectorAll('#trick .played').forEach(card=>{if(card.dataset.decorated)return;const raw=card.textContent.replace(/\s+/g,' ').trim();const m=raw.match(/(10|[2-9]|J|Q|K|A)([♠♥♦♣])$/);if(!m)return;const rank=m[1],suit=m[2],label=raw.slice(0,raw.length-m[0].length).trim();card.textContent='';const l=document.createElement('small');l.textContent=label;card.append(l,cardFace(rank,suit));card.dataset.decorated='1';});}
function buildLandingV2(){const old=document.getElementById('landing');if(!old||old.dataset.v2)return;old.dataset.v2='1';old.className='landing-shell landing-v2';old.innerHTML=`<div class="v2-top"><div class="v2-brand"><div class="v2-logo">♠♥</div><div><strong>المحترفين</strong><small>طرنيب احترافي</small></div></div><div class="v2-online"><i></i><span>متصل الآن · 1,248 لاعب</span></div><button class="v2-lang" type="button">العربية ▾</button></div><section class="v2-hero"><div class="v2-kicker">تجربة طرنيب من الجيل الجديد</div><h1 class="v2-title">المحترفين <em>في الطرنيب</em></h1><p class="v2-copy">طاولة واقعية، ورق واضح، لعب سلس ومنافسة أشرس.</p><div class="v2-stage"><div class="v2-table"></div><div class="v2-card one">♥</div><div class="v2-card two">♠</div><div class="v2-card three">♦</div><div class="v2-medal"><div><span>♠</span><small>PRO</small></div></div><div class="v2-live"><b>1,248</b> لاعبون الآن</div></div><div class="v2-actions"><button class="btn btn-primary" onclick="guestPlay()">🎮 دخول تجريبي — العب الآن</button><button class="btn btn-secondary" onclick="openLogin()">🔐 تسجيل الدخول</button></div><button class="btn v2-create" onclick="openSignup()">✦ إنشاء حساب جديد</button><p class="v2-hint">✓ جرّب الطاولة مباشرة بدون تسجيل</p></section><h2 class="v2-section-title">ميزات <em>المحترفين</em></h2><div class="v2-grid"><button class="v2-feature purple" onclick="openSocial('profile')"><div class="v2-icon">👤</div><strong>ملفي</strong><span>صفحتك الشخصية</span></button><button class="v2-feature purple" onclick="openSocial('feed')"><div class="v2-icon">📰</div><strong>المنشورات</strong><span>شارك وتفاعل</span></button><button class="v2-feature blue" onclick="openSocial('friends')"><div class="v2-icon">👥</div><strong>الأصدقاء</strong><span>قائمة أصدقائك</span></button><button class="v2-feature gold" onclick="openSocial('vip')"><div class="v2-icon">♛</div><strong>VIP</strong><span>عضويات ومزايا</span></button><button class="v2-feature green" onclick="openSocial('nearby')"><div class="v2-icon">📍</div><strong>القريبون</strong><span>أشخاص بالقرب منك</span></button><div class="v2-feature blue"><div class="v2-icon">▣</div><strong>المحفظة</strong><span>عملاتك ورصيدك</span></div><div class="v2-feature gold"><div class="v2-icon">🏆</div><strong>البطولات</strong><span>شارك واربح الجوائز</span></div><div class="v2-feature purple"><div class="v2-icon">💬</div><strong>الدردشة</strong><span>دردش مع اللاعبين</span></div></div><div class="v2-trust"><div><b>🛡 لعبة آمنة</b>حماية وخصوصية</div><div><b>◉ 24/7 دعم</b>مساعدة مستمرة</div><div><b>↻ تحديثات</b>ميزات جديدة دائماً</div></div><nav class="v2-nav"><button class="main">⌂<span>الرئيسية</span></button><button>🃏<span>غرف اللعب</span></button><button class="play" onclick="guestPlay()">▶</button><button>✉<span>الرسائل</span></button><button>⚙<span>الإعدادات</span></button></nav>`}
function enhance(){decorateHand();decorateTrick();buildLandingV2()}
const obs=new MutationObserver(enhance);obs.observe(document.body,{subtree:true,childList:true});enhance();