// Tarneeb rules engine: standard 52-card deck, 4 players, 13 cards each.
export const SUITS=['♠','♥','♦','♣'];
export const RANKS=['2','3','4','5','6','7','8','9','10','J','Q','K','A'];
const VALUE=Object.fromEntries(RANKS.map((r,i)=>[r,i+2]));
export function createDeck(){return SUITS.flatMap(s=>RANKS.map(r=>({s,r,v:VALUE[r]})));}
export function shuffle(deck){const a=deck.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function dealHands(){const hands=[[],[],[],[]];shuffle(createDeck()).forEach((c,i)=>hands[i%4].push(c));hands.forEach(h=>h.sort((a,b)=>SUITS.indexOf(a.s)-SUITS.indexOf(b.s)||b.v-a.v));return hands;}
export function isSameCard(a,b){return !!a&&!!b&&a.s===b.s&&a.r===b.r;}
export function isLegalBid(state,player,bid){if(state.phase!=='bid'||state.bidTurn!==player)return false;if(bid===null)return true;return Number.isInteger(bid)&&bid>=7&&bid<=13&&bid>(state.highBid??6);}
export function applyBid(state,player,bid){if(!isLegalBid(state,player,bid))throw new Error('Illegal bid');const next=structuredClone(state);next.bids[player]=bid;if(bid!==null&&bid>next.highBid){next.highBid=bid;next.bidWinner=player;}next.bidTurn=(player+1)%4;if(next.bidTurn===next.bidStart){if(next.bidWinner===null)throw new Error('At least one player must bid');next.phase='trump';next.turn=next.bidWinner;}return next;}
export function isLegalTrump(state,player,trump){return state.phase==='trump'&&player===state.bidWinner&&SUITS.includes(trump);}
export function setTrump(state,player,trump){if(!isLegalTrump(state,player,trump))throw new Error('Illegal trump');const next=structuredClone(state);next.trump=trump;next.phase='play';next.turn=player;return next;}
export function legalCards(state,player){if(state.phase!=='play'||state.turn!==player)return [];const hand=state.players[player].hand;if(!state.leadSuit)return hand.slice();const following=hand.filter(c=>c.s===state.leadSuit);return following.length?following:hand.slice();}
export function isLegalCard(state,player,card){return legalCards(state,player).some(c=>isSameCard(c,card));}
export function cardBeats(candidate,currentWinner,leadSuit,trump){if(!currentWinner)return true;const cTrump=candidate.s===trump,wTrump=currentWinner.s===trump;if(cTrump!==wTrump)return cTrump;if(candidate.s===currentWinner.s)return candidate.v>currentWinner.v;if(candidate.s===leadSuit&&currentWinner.s!==leadSuit)return true;return false;}
export function trickWinner(trick,leadSuit,trump){if(!trick.length)throw new Error('Cannot score empty trick');let best=trick[0];for(const play of trick.slice(1))if(cardBeats(play.card,best.card,leadSuit,trump))best=play;return best.player;}
export function scoreRound(state){if(state.trickNo!==13)throw new Error('Round is not finished');const bidder=state.bidWinner,team=state.players[bidder].team,bid=state.highBid,made=state.players.filter(p=>p.team===team).reduce((n,p)=>n+p.tricks,0),other=13-made,scores=state.scores.slice();if(made>=bid)scores[team]+=made;else scores[team]-=bid;scores[1-team]+=other;return{bidder,team,bid,made,other,scores};}
export function applyCard(state,player,card){if(!isLegalCard(state,player,card))throw new Error('Illegal card');const next=structuredClone(state),hand=next.players[player].hand,idx=hand.findIndex(c=>isSameCard(c,card));if(idx<0)throw new Error('Card not in hand');const played=hand.splice(idx,1)[0];if(!next.leadSuit)next.leadSuit=played.s;next.trick.push({player,card:played});if(next.trick.length===4){const winner=trickWinner(next.trick,next.leadSuit,next.trump);next.players[winner].tricks++;next.lastTrickWinner=winner;next.turn=winner;next.trick=[];next.leadSuit=null;next.trickNo++;if(next.trickNo===13){next.phase='round_end';next.roundResult=scoreRound(next);}}else next.turn=(player+1)%4;return next;}
export function newState(hands,bidStart=0,scores=[0,0]){if(!Array.isArray(hands)||hands.length!==4||hands.some(h=>h.length!==13))throw new Error('Tarneeb requires four 13-card hands');return{phase:'bid',players:hands.map((hand,i)=>({team:i%2,hand:hand.slice(),tricks:0})),bidStart,bidTurn:bidStart,highBid:6,bids:[null,null,null,null],bidWinner:null,trump:null,turn:bidStart,leadSuit:null,trick:[],trickNo:0,scores:scores.slice()};}

// Browser bridge: when the room's Start button is assigned by index.html, replace the old
// local-only handler with a real four-player Supabase game. Guest/AI play is untouched.
if(typeof window!=='undefined'){
  const ONLINE_URL='https://gzgngkywjyanxicmwxlc.supabase.co';
  const ONLINE_KEY='sb_publishable_Jyr7D3mH7WRXfG5V1v7gcw_I3QhtL3j';
  let onlineGameId=null,onlineChannel=null,onlineSupabase=null;
  const esc=s=>String(s).replace(/'/g,"\\'");
  async function onlineClient(){if(!onlineSupabase){const m=await import('https://esm.sh/@supabase/supabase-js@2');onlineSupabase=m.createClient(ONLINE_URL,ONLINE_KEY);}return onlineSupabase;}
  async function onlineAction(action,value){const sb=await onlineClient();const{data,error}=await sb.rpc('tarneeb_apply_action',{p_game_id:onlineGameId,p_action:action,p_value:value||null});if(error)throw error;return data;}
  function onlineMsg(t){const e=document.getElementById('msg');if(e)e.textContent=t||'';}
  async function onlineState(){const sb=await onlineClient();const g=await sb.from('tarneeb_games').select('id,status,current_seat,bid,bidder_seat,trump,trick_no,team1_score,team2_score,state,room_code').eq('id',onlineGameId).single();if(g.error)throw g.error;const me=await sb.rpc('tarneeb_current_player',{p_game_id:onlineGameId});let player=me.data;if(Array.isArray(player))player=player[0];if(!player){const q=await sb.from('tarneeb_players').select('seat,hand,tricks,bid,user_id').eq('game_id',onlineGameId);const session=await sb.auth.getSession();player=(q.data||[]).find(p=>p.user_id===session.data.session?.user.id);}
    return{game:g.data,me:player};}
  function renderOnline(v){const g=v.game,s=g.state||{},me=v.me;if(!me)return;document.getElementById('score0').textContent=g.team1_score||0;document.getElementById('score1').textContent=g.team2_score||0;document.getElementById('roundLabel').textContent=`غرفة ${g.room_code} · الأكلة ${g.trick_no||0}/13`;const seat=me.seat,phase=s.phase,current=g.current_seat;document.getElementById('stateInfo').textContent=phase==='bid'?`المزايدة: دور اللاعب ${s.bid_turn||current} · أعلى طلب ${s.high_bid>=7?s.high_bid:'—'}`:phase==='trump'?`اللاعب ${s.bid_winner} يختار الحكم`:phase==='play'?`الحكم: ${s.trump||'—'} · الدور: اللاعب ${current}`:`انتهت الجولة`;document.getElementById('bidBox').classList.toggle('hidden',!(phase==='bid'&&current===seat));document.getElementById('trumpBox').classList.toggle('hidden',!(phase==='trump'&&current===seat));document.getElementById('bidInfo').textContent=`دورك · أعلى طلب ${s.high_bid>=7?s.high_bid:'لا يوجد'}`;document.getElementById('bids').innerHTML=[7,8,9,10,11,12,13].map(n=>`<button ${n<=Number(s.high_bid||6)?'disabled':''} onclick="window.__onlineBid(${n})">${n}</button>`).join('')+`<button class="secondary" onclick="window.__onlinePass()">مرور</button>`;document.getElementById('trumps').innerHTML=SUITS.map(x=>`<button onclick="window.__onlineTrump('${esc(x)}')">${x}</button>`).join('');const trick=s.trick||[];document.getElementById('trick').innerHTML=trick.map(x=>`<div class="played">لاعب ${x.seat}<br><span>${x.card.r+x.card.s}</span></div>`).join('');const hand=me.hand||[];const legal=phase==='play'&&current===seat?onlineLegalCards(hand,s):[];document.getElementById('hand').innerHTML=hand.map((c,i)=>{const ok=legal.some(x=>x.s===c.s&&x.r===c.r);return `<button class="cardplay ${c.s==='♥'||c.s==='♦'?'red':''}" ${ok?'':'disabled'} onclick="window.__onlineCard(${i})">${c.r+c.s}</button>`}).join('');}
  function onlineLegalCards(hand,s){if(!s.lead_suit)return hand;if(hand.some(c=>c.s===s.lead_suit))return hand.filter(c=>c.s===s.lead_suit);return hand;}
  async function refreshOnline(){try{const v=await onlineState();renderOnline(v);}catch(e){onlineMsg(e.message||String(e));}}
  async function startOnline(){try{const code=(document.getElementById('code')?.textContent||'').trim();if(!code)throw new Error('رمز الغرفة غير موجود');const sb=await onlineClient();const{data,error}=await sb.rpc('tarneeb_start_game',{p_room_code:code});if(error)throw error;onlineGameId=data;document.getElementById('home')?.classList.add('hidden');document.getElementById('room')?.classList.add('hidden');document.getElementById('game')?.classList.remove('hidden');if(onlineChannel)await sb.removeChannel(onlineChannel);onlineChannel=sb.channel('tarneeb-game-'+onlineGameId).on('postgres_changes',{event:'*',schema:'public',table:'tarneeb_games',filter:'id=eq.'+onlineGameId},refreshOnline).on('postgres_changes',{event:'*',schema:'public',table:'tarneeb_players',filter:'game_id=eq.'+onlineGameId},refreshOnline).subscribe();await refreshOnline();}catch(e){onlineMsg(e.message||String(e));}}
  Object.defineProperty(window,'startRoomGame',{configurable:true,set(fn){Object.defineProperty(window,'startRoomGame',{configurable:true,writable:true,value:startOnline});},get(){return startOnline;}});
  window.__onlineBid=async n=>{try{await onlineAction('bid',{bid:n});await refreshOnline();}catch(e){onlineMsg(e.message||String(e));}};
  window.__onlinePass=async()=>{try{await onlineAction('pass',{});await refreshOnline();}catch(e){onlineMsg(e.message||String(e));}};
  window.__onlineTrump=async s=>{try{await onlineAction('trump',{suit:s});await refreshOnline();}catch(e){onlineMsg(e.message||String(e));}};
  window.__onlineCard=async i=>{try{const v=await onlineState();const c=(v.me.hand||[])[i];if(!c)throw new Error('الورقة غير موجودة');await onlineAction('card',{suit:c.s,rank:c.r});await refreshOnline();}catch(e){onlineMsg(e.message||String(e));}};
}
